name: frederick-cas
domains:
- domain: ${DOMAIN}
  type: PRIMARY

services:
- name: api
  github:
    repo: adamcamp/frederick-cas
    branch: develop
    deploy_on_push: true
  dockerfile_path: Dockerfile
  envs:
  - key: RAILS_ENV
    scope: RUN_TIME
    value: production
  - key: SECRET_KEY_BASE
    scope: RUN_TIME
    value: ${SECRET_KEY_BASE}
  - key: DATABASE_SSLMODE
    scope: RUN_TIME
    value: require
  - key: DATABASE_MAINTENANCE_DB
    scope: RUN_TIME
    value: db
  - key: DATABASE_URL
    scope: RUN_TIME
    value: postgres://${db.USERNAME}:${db.PASSWORD}@${db.HOSTNAME}:${db.PORT}/${db.DATABASE}
  - key: REDIS_URL
    scope: RUN_TIME
    value: redis://${cache.USERNAME}:${cache.PASSWORD}@${cache.HOSTNAME}:${cache.PORT}
  - key: HOSTNAME
    scope: RUN_TIME
    value: ${DOMAIN}
  - key: FQDN
    scope: RUN_TIME
    value: ${DOMAIN}
  - key: CLIENT
    scope: RUN_TIME
    value: Frederick CAS
  - key: TIMEZONE
    scope: RUN_TIME
    value: America/New_York
  - key: DEFAULT_FROM
    scope: RUN_TIME
    value: '"No Reply" <no-reply@${EMAIL_DOMAIN}>'
  - key: SMTP_SERVER
    scope: RUN_TIME
    value: smtp.sendgrid.net
  - key: SMTP_DOMAIN
    scope: RUN_TIME
    value: ${DOMAIN}
  - key: SMTP_PORT
    scope: RUN_TIME
    value: "587"
  - key: SENDGRID_API_KEY
    scope: RUN_TIME
    value: ${SENDGRID_API_KEY}
  http_port: 3000
  health_check:
    http_path: /health
  routes:
  - path: /api
    preserve_path_prefix: false
  run_command: |
    bundle exec rake db:create db:migrate
    exec bundle exec puma -c config/puma.rb

- name: warehouse
  github:
    repo: adamcamp/hmis-warehouse
    branch: develop
    deploy_on_push: true
  dockerfile_path: Dockerfile
  envs:
  - key: RAILS_ENV
    scope: RUN_TIME
    value: production
  - key: SECRET_KEY_BASE
    scope: RUN_TIME
    value: ${WAREHOUSE_SECRET_KEY_BASE}
  - key: DATABASE_SSLMODE
    scope: RUN_TIME
    value: require
  - key: DATABASE_MAINTENANCE_DB
    scope: RUN_TIME
    value: db
  - key: DATABASE_ADAPTER
    scope: RUN_TIME
    value: postgresql
  - key: DATABASE_APP_DB
    scope: RUN_TIME
    value: frederick_warehouse_production
  - key: DATABASE_HOST
    scope: RUN_TIME
    value: ${db.HOSTNAME}
  - key: DATABASE_PORT
    scope: RUN_TIME
    value: ${db.PORT}
  - key: DATABASE_USER
    scope: RUN_TIME
    value: ${db.USERNAME}
  - key: DATABASE_PASS
    scope: RUN_TIME
    value: ${db.PASSWORD}
  - key: WAREHOUSE_DATABASE_ADAPTER
    scope: RUN_TIME
    value: postgis
  - key: WAREHOUSE_DATABASE_DB
    scope: RUN_TIME
    value: frederick_warehouse_data_production
  - key: WAREHOUSE_DATABASE_HOST
    scope: RUN_TIME
    value: ${db.HOSTNAME}
  - key: WAREHOUSE_DATABASE_PORT
    scope: RUN_TIME
    value: ${db.PORT}
  - key: WAREHOUSE_DATABASE_USER
    scope: RUN_TIME
    value: ${db.USERNAME}
  - key: WAREHOUSE_DATABASE_PASS
    scope: RUN_TIME
    value: ${db.PASSWORD}
  - key: HEALTH_DATABASE_ADAPTER
    scope: RUN_TIME
    value: postgresql
  - key: HEALTH_DATABASE_DB
    scope: RUN_TIME
    value: frederick_health_production
  - key: HEALTH_DATABASE_HOST
    scope: RUN_TIME
    value: ${db.HOSTNAME}
  - key: HEALTH_DATABASE_PORT
    scope: RUN_TIME
    value: ${db.PORT}
  - key: HEALTH_DATABASE_USER
    scope: RUN_TIME
    value: ${db.USERNAME}
  - key: HEALTH_DATABASE_PASS
    scope: RUN_TIME
    value: ${db.PASSWORD}
  - key: REPORTING_DATABASE_ADAPTER
    scope: RUN_TIME
    value: postgresql
  - key: REPORTING_DATABASE_DB
    scope: RUN_TIME
    value: frederick_reporting_production
  - key: REPORTING_DATABASE_HOST
    scope: RUN_TIME
    value: ${db.HOSTNAME}
  - key: REPORTING_DATABASE_PORT
    scope: RUN_TIME
    value: ${db.PORT}
  - key: REPORTING_DATABASE_USER
    scope: RUN_TIME
    value: ${db.USERNAME}
  - key: REPORTING_DATABASE_PASS
    scope: RUN_TIME
    value: ${db.PASSWORD}
  - key: CAS_DATABASE_ADAPTER
    scope: RUN_TIME
    value: postgresql
  - key: CAS_DATABASE_DB
    scope: RUN_TIME
    value: frederick_cas_production
  - key: CAS_DATABASE_HOST
    scope: RUN_TIME
    value: ${db.HOSTNAME}
  - key: CAS_DATABASE_PORT
    scope: RUN_TIME
    value: ${db.PORT}
  - key: CAS_DATABASE_USER
    scope: RUN_TIME
    value: ${db.USERNAME}
  - key: CAS_DATABASE_PASS
    scope: RUN_TIME
    value: ${db.PASSWORD}
  - key: REDIS_URL
    scope: RUN_TIME
    value: redis://${cache.USERNAME}:${cache.PASSWORD}@${cache.HOSTNAME}:${cache.PORT}
  - key: HOSTNAME
    scope: RUN_TIME
    value: ${DOMAIN}
  - key: FQDN
    scope: RUN_TIME
    value: ${DOMAIN}
  - key: CLIENT
    scope: RUN_TIME
    value: Frederick HMIS Warehouse
  - key: TIMEZONE
    scope: RUN_TIME
    value: America/New_York
  - key: DEFAULT_FROM
    scope: RUN_TIME
    value: '"No Reply" <noreply@${EMAIL_DOMAIN}>'
  - key: SMTP_SERVER
    scope: RUN_TIME
    value: smtp.sendgrid.net
  - key: SMTP_DOMAIN
    scope: RUN_TIME
    value: ${DOMAIN}
  - key: SMTP_PORT
    scope: RUN_TIME
    value: "587"
  - key: SENDGRID_API_KEY
    scope: RUN_TIME
    value: ${SENDGRID_API_KEY}
  - key: S3_ENDPOINT
    scope: RUN_TIME
    value: https://${SPACES_REGION}.digitaloceanspaces.com
  - key: S3_TMP_BUCKET
    scope: RUN_TIME
    value: ${SPACES_TMP_BUCKET}
  - key: S3_TMP_ACCESS_KEY_ID
    scope: RUN_TIME
    value: ${SPACES_ACCESS_KEY_ID}
  - key: S3_TMP_ACCESS_KEY_SECRET
    scope: RUN_TIME
    value: ${SPACES_SECRET_ACCESS_KEY}
  - key: S3_TMP_REGION
    scope: RUN_TIME
    value: ${SPACES_REGION}
  - key: S3_PUBLIC_BUCKET
    scope: RUN_TIME
    value: ${SPACES_PUBLIC_BUCKET}
  - key: S3_PUBLIC_ACCESS_KEY_ID
    scope: RUN_TIME
    value: ${SPACES_ACCESS_KEY_ID}
  - key: S3_PUBLIC_ACCESS_KEY_SECRET
    scope: RUN_TIME
    value: ${SPACES_SECRET_ACCESS_KEY}
  - key: S3_PUBLIC_REGION
    scope: RUN_TIME
    value: ${SPACES_REGION}
  - key: S3_PUBLIC_URL
    scope: RUN_TIME
    value: https://${SPACES_PUBLIC_BUCKET}.${SPACES_REGION}.digitaloceanspaces.com/
  http_port: 3000
  health_check:
    http_path: /health
  routes:
  - path: /warehouse
    preserve_path_prefix: true
  run_command: |
    bundle exec rake db:create db:migrate
    exec bundle exec puma -c config/puma.rb

static_sites:
- name: web
  github:
    repo: adamcamp/hmis-frontend
    branch: develop
    deploy_on_push: true
  build_command: HUSKY=0 yarn install --frozen-lockfile && yarn build
  output_dir: dist
  envs:
  - key: VITE_APP_URL
    value: https://${DOMAIN}
  - key: VITE_API_URL
    value: https://${DOMAIN}/api/graphql
  - key: VITE_WAREHOUSE_URL
    value: https://${DOMAIN}/warehouse

databases:
- name: db
  engine: PG
  version: "14"
  db_name: postgres
  

- name: cache
  engine: VALKEY
  version: "8"
  production: true
  cluster_name: ${CACHE_CLUSTER_NAME}

envs:
# Shared environment variables
- key: DOMAIN
  scope: RUN_TIME
  value: frederick-cas.adamsworlds.com
- key: EMAIL_DOMAIN
  scope: RUN_TIME
  value: adamsworlds.com
- key: RAILS_LOG_TO_STDOUT
  scope: RUN_TIME
  value: "true"
- key: MAIL_DELIVERY_METHOD
  scope: RUN_TIME
  value: smtp
